name: Python CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.7'
    - name: install-dependencies
      run: pip install pytest
    - run: pytest
      working-directory: app
      
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.7'
    - name: install-dependencies
      run: pip install black
    - run: black
      working-directory: app